main: net.battlenexus.paintball.Paintball
name: Paintball
version: 1.0.0
description: Paintball plugin
author: BattleNexus
authors: [Lavoaster, BeMacized, Wouter1997, hypereddie10]
commands:
   createpbmap:
      aliases:
        - cpbmap
      description: Create a new paintball map.
      usage: /<command>
   join:
     description: Join the paintball queue.
     usage: /<command>
   leave:
     description: Leaves the paintball queue.
     usage: /<command>
   signstat:
     description: Place a sign with game stats.
     usage: /<command>